
project_id = "xltxqqzattxogxtqrggt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[transformers]]
extensions = ["ts", "tsx"]
handler = "npx esbuild --loader=tsx --format=esm --platform=neutral --bundle {{source}} > {{target}}"

[functions.validate-zip]
verify_jwt = false
