
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "car-detective-mvp"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "extensions"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["extensions"]
# Maximum rows to return from a view, table, or stored procedure. Limits payload size for accidental
# or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by database to accept connections.
server_port = 5432
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# The maximum number of database connections that can be maintained by the pooler at any given time.
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv6)
# ip_version = "IPv6"

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://127.0.0.1"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://127.0.0.1:5173"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://127.0.0.1:5173"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

[auth.external.apple]
enabled = false
# Overrides the default auth flow to use Apple's proprietary flow. Only enable if you have issues
# with the standard flow.
use_proprietary_flow = false
# The scopes that are required from the end-user when connecting to Apple.
scopes = ["name", "email"]

[auth.external.azure]
enabled = false
# The scopes that are required from the end-user when connecting to Azure.
scopes = ["email", "profile"]

[auth.external.bitbucket]
enabled = false
# The scopes that are required from the end-user when connecting to Bitbucket.
scopes = ["account", "email"]

[auth.external.discord]
enabled = false
# The scopes that are required from the end-user when connecting to Discord.
scopes = ["identify", "email"]

[auth.external.facebook]
enabled = false
# The scopes that are required from the end-user when connecting to Facebook.
scopes = ["email"]

[auth.external.github]
enabled = false
# The scopes that are required from the end-user when connecting to GitHub.
scopes = ["user:email"]

[auth.external.gitlab]
enabled = false
# The scopes that are required from the end-user when connecting to GitLab.
scopes = ["read_user"]

[auth.external.google]
enabled = false
# The scopes that are required from the end-user when connecting to Google.
scopes = ["email", "profile"]

[auth.external.keycloak]
enabled = false
# The scopes that are required from the end-user when connecting to Keycloak.
scopes = ["email", "profile"]

[auth.external.linkedin]
enabled = false
# The scopes that are required from the end-user when connecting to LinkedIn.
scopes = ["r_emailaddress", "r_liteprofile"]

[auth.external.notion]
enabled = false
# The scopes that are required from the end-user when connecting to Notion.
scopes = []

[auth.external.twitch]
enabled = false
# The scopes that are required from the end-user when connecting to Twitch.
scopes = ["user:read:email"]

[auth.external.twitter]
enabled = false

[auth.external.slack]
enabled = false
# The scopes that are required from the end-user when connecting to Slack.
scopes = ["users.profile:read", "team:read"]

[auth.external.spotify]
enabled = false
# The scopes that are required from the end-user when connecting to Spotify.
scopes = ["user-read-email"]

[auth.external.workos]
enabled = false
# The scopes that are required from the end-user when connecting to WorkOS.
scopes = ["email", "profile"]

[auth.external.zoom]
enabled = false
# The scopes that are required from the end-user when connecting to Zoom.
scopes = ["user:read"]

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of these backends
backend = "postgres"
# backend = "bigquery"

# Experimental features may change behavior and are not guaranteed to be stable.
# We encourage feedback on these features.
[experimental]
# OpenAI-compatible PostgresML AI proxy
ai_proxy = false
# External oauth provider support
external_oauth_providers = false

# Configure Postgres identity provider
[identity]
enabled = false

# Configure functions directory
[functions]
port = 54326

# Configure Supabase CLI telemetry
[telemetry]
enabled = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true
