
project_id = "xltxqqzattxogxtqrggt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true

[functions]
[functions.trigger-email-campaign]
verify_jwt = true

[functions.schedule-email-campaigns]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-public-token]
verify_jwt = true
