project_id = "xltxqqzattxogxtqrggt"

[functions.fetch-vehicle-history]
verify_jwt = false

[functions.fetch-market-listings]
verify_jwt = false

[functions.valuation-forecast]
verify_jwt = true

[functions.decode-vin]
verify_jwt = false

[functions.unified-decode]
verify_jwt = false

[functions.predict]
verify_jwt = false
