
project_id = "xltxqqzattxogxtqrggt"

[functions.vehicle_history_functions]
verify_jwt = false

[functions.fetch_nicb_vincheck]
verify_jwt = true

[functions.fetch_vpic_data]
verify_jwt = true

[functions.fetch_nhtsa_recalls]
verify_jwt = false

[functions.fetch_zippopotamus]
verify_jwt = false

[functions.fetch_epa_mpg]
verify_jwt = false

[functions.fetch_osm_geocode]
verify_jwt = false

[functions.fetch_census_demographics]
verify_jwt = false

[functions.fetch_auction_index]
verify_jwt = false

[functions.daily_calibration]
verify_jwt = true
