name: Clean CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python deps
        run: |
          pip install -r requirements.txt
          pip install pytest flake8
      
      - name: Lint Python
        run: flake8 . --exclude=venv,node_modules
        continue-on-error: true
      
      - name: Test Python
        run: pytest --disable-warnings
        continue-on-error: true
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Node deps
        run: npm ci
      
      - name: Test Node.js
        run: npm test
        continue-on-error: true
      
      - name: Build Docker
        run: docker build -t app .
        continue-on-error: true