name: AIN Valuation Engine

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Only run when secrets exist (prevents login failure)
    if: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Login (optional)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push (optional)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: yourorg/ain-valuation-engine:latest
