name: CI Gates
on:
  pull_request: { branches: [ "main" ] }
  push: { branches: [ "main" ] }
concurrency: { group: ci-${{ github.ref }}, cancel-in-progress: true }
jobs:
  js_ts_tests:
    name: JS/TS Unit Tests (Jest + ts-jest)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: "npm" }
      - run: npm ci || npm i
      - run: npx tsc --noEmit || echo "tsconfig missing or TS not installed"
      - run: npm test -- --coverage || npx jest --coverage
      - uses: actions/upload-artifact@v4
        with: { name: coverage-js, path: coverage/js, if-no-files-found: ignore }
  deno_functions:
    name: Deno Edge Functions (lint + check + test)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults: { run: { working-directory: supabase/functions } }
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with: { deno-version: v1.x }
      - run: deno lint
      - run: deno check $(git ls-files "*.ts" "*.tsx")
      - run: deno test --allow-env --allow-net --coverage=coverage/deno || echo "No Deno tests"
      - uses: actions/upload-artifact@v4
        if: always()
        with: { name: coverage-deno, path: supabase/functions/coverage/deno, if-no-files-found: ignore }
  python_tests:
    name: Python Tests + Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install pytest coverage pytest-cov pip-audit
      - env: { PYTHONPATH: . }
        run: |
          pytest || true
          coverage report --fail-under=80 || exit 1
      - uses: actions/upload-artifact@v4
        with: { name: coverage-python, path: coverage/python, if-no-files-found: ignore }
  openapi_contract:
    name: OpenAPI Contract Tests (Schemathesis)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install schemathesis==3.25.2
      - run: |
          nohup python -m api.run --port 8000 >/tmp/api.log 2>&1 & disown || true
          sleep 6
          tail -n +1 -f /tmp/api.log | sed -u 's/^/[api] /' &  # non-fatal
      - env: { BASE_URL: "http://127.0.0.1:8000" }
        run: |
          OPENAPI_PATH="${{ github.workspace }}/openapi/openapi.yaml"
          test -f "$OPENAPI_PATH" || { echo "No openapi.yaml, skipping"; exit 0; }
          schemathesis run "$OPENAPI_PATH" --base-url "$BASE_URL" --checks all --stateful=links --hypothesis-deadline=800
  security_compliance:
    name: Security & Compliance (Secrets, SBOM, Dependency Audit)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - run: curl -sSL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | bash -s -- -b /usr/local/bin
      - run: gitleaks detect --verbose --redact --no-git -s . || (echo "Secrets found" && exit 1)
      - uses: anchore/sbom-action@v0
        with: { path: ., format: spdx-json, output-file: sbom.spdx.json }
      - uses: actions/upload-artifact@v4
        with: { name: sbom-spdx, path: sbom.spdx.json }
      - run: npm audit --audit-level=high || (echo "High vulns found" && exit 1)
      - run: pip-audit || (echo "Python vulns found" && exit 1)
  enforce_status:
    name: Enforce All Gates
    runs-on: ubuntu-latest
    needs: [ js_ts_tests, deno_functions, python_tests, openapi_contract, security_compliance ]
    steps:
      - run: echo "All gates passed ✅"
