openapi: 3.0.3
info:
  title: AIN Valuation API
  description: |
    Vehicle identification and valuation API with comprehensive VIN decoding,
    recalls, safety ratings, and fuel economy data.
  version: 1.0.0
  contact:
    name: AIN Development Team
    email: dev@ain-valuation.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://{host}/v1
    description: Production API
    variables:
      host:
        default: api.ain-valuation.com
        description: API host
  - url: https://{host}/v1
    description: Development API
    variables:
      host:
        default: dev-api.ain-valuation.com

security:
  - ApiKeyAuth: []
  - BearerAuth: []

paths:
  /decode-vin:
    post:
      operationId: decodeVin
      summary: Decode Vehicle Identification Number
      description: |
        Decodes a VIN using NHTSA vPIC API with fallback mechanisms.
        Returns comprehensive vehicle specifications and metadata.
      tags:
        - VIN Decoding
      parameters:
        - in: header
          name: X-Request-Id
          description: Unique request identifier for correlation
          schema:
            type: string
            format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        - in: header
          name: Idempotency-Key
          description: Idempotency key for safe retries
          schema:
            type: string
          example: "decode-vin-1234567890"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [vin]
              properties:
                vin:
                  type: string
                  pattern: '^[A-HJ-NPR-Z0-9]{17}$'
                  description: 17-character Vehicle Identification Number
                  example: "1HGCM82633A004352"
                options:
                  type: object
                  properties:
                    forceRefresh:
                      type: boolean
                      default: false
                      description: Force refresh of cached data
                    timeout:
                      type: integer
                      minimum: 1000
                      maximum: 30000
                      default: 10000
                      description: Request timeout in milliseconds
      responses:
        "200":
          description: VIN successfully decoded
          headers:
            X-Request-Id:
              schema:
                type: string
            X-Rate-Limit-Remaining:
              schema:
                type: integer
              description: Requests remaining in current window
            X-Rate-Limit-Reset:
              schema:
                type: integer
              description: Rate limit reset time (Unix timestamp)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VinDecodeResponse'
        "400":
          $ref: '#/components/responses/BadRequest'
        "422":
          description: VIN validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: "VALIDATION_FAILED"
                  message: "VIN check digit validation failed"
                  details:
                    vin: "1HGCM82633A004353"
                    expectedCheckDigit: "2"
                    actualCheckDigit: "3"
        "429":
          $ref: '#/components/responses/TooManyRequests'
        "503":
          description: Upstream service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /vehicle-profile/{vin}:
    get:
      operationId: getVehicleProfile
      summary: Get comprehensive vehicle profile
      description: |
        Returns complete vehicle profile including specifications,
        recalls, safety ratings, and fuel economy data.
      tags:
        - Vehicle Profiles
      parameters:
        - in: path
          name: vin
          required: true
          description: 17-character Vehicle Identification Number
          schema:
            type: string
            pattern: '^[A-HJ-NPR-Z0-9]{17}$'
          example: "1HGCM82633A004352"
        - in: header
          name: X-Request-Id
          schema:
            type: string
            format: uuid
        - in: query
          name: include
          description: Comma-separated list of data to include
          schema:
            type: string
            enum: [specs, recalls, safety, fuel, all]
            default: all
          example: "specs,recalls,safety"
        - in: query
          name: maxAge
          description: Maximum age of cached data in seconds
          schema:
            type: integer
            minimum: 0
            default: 3600
      responses:
        "200":
          description: Vehicle profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleProfile'
        "404":
          description: Vehicle not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "400":
          $ref: '#/components/responses/BadRequest'
        "429":
          $ref: '#/components/responses/TooManyRequests'

  /health:
    get:
      operationId: healthCheck
      summary: API health check
      description: Returns API health status and dependency checks
      tags:
        - System
      responses:
        "200":
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy, degraded]
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string
                  dependencies:
                    type: object
                    properties:
                      database:
                        type: string
                        enum: [up, down, degraded]
                      nhtsa_api:
                        type: string
                        enum: [up, down, degraded]
                      cache:
                        type: string
                        enum: [up, down, degraded]

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    VinDecodeResponse:
      type: object
      required: [vin, decodedAt, source, data, metadata]
      properties:
        vin:
          type: string
          description: Normalized VIN
          example: "1HGCM82633A004352"
        decodedAt:
          type: string
          format: date-time
          description: When the VIN was decoded
        source:
          type: string
          enum: [VPIC, EDGE_CACHE, DIRECT, CACHED]
          description: Data source used for decoding
        data:
          type: object
          description: Decoded vehicle specifications
          properties:
            make:
              type: string
              example: "HONDA"
            model:
              type: string
              example: "Accord"
            modelYear:
              type: integer
              example: 2003
            trim:
              type: string
              example: "EX"
            bodyClass:
              type: string
              example: "Sedan"
            engineCylinders:
              type: integer
              example: 6
            fuelTypePrimary:
              type: string
              example: "Gasoline"
            driveType:
              type: string
              example: "Front-Wheel Drive"
            transmissionStyle:
              type: string
              example: "Automatic"
            plantCountry:
              type: string
              example: "UNITED STATES (USA)"
        metadata:
          type: object
          properties:
            requestId:
              type: string
            cacheHit:
              type: boolean
            processingTimeMs:
              type: integer
            errorCode:
              type: string
            errorText:
              type: string

    VehicleProfile:
      type: object
      required: [vin, profile]
      properties:
        vin:
          type: string
          example: "1HGCM82633A004352"
        profile:
          type: object
          properties:
            specs:
              $ref: '#/components/schemas/VehicleSpecs'
            recalls:
              type: array
              items:
                $ref: '#/components/schemas/RecallInfo'
            safety:
              $ref: '#/components/schemas/SafetyRating'
            fuelEconomy:
              $ref: '#/components/schemas/FuelEconomy'
            lastUpdated:
              type: string
              format: date-time

    VehicleSpecs:
      type: object
      properties:
        make:
          type: string
        model:
          type: string
        modelYear:
          type: integer
        trim:
          type: string
        bodyClass:
          type: string
        engineCylinders:
          type: integer
        fuelTypePrimary:
          type: string
        driveType:
          type: string
        transmissionStyle:
          type: string
        plantCountry:
          type: string

    RecallInfo:
      type: object
      properties:
        campaignId:
          type: string
        component:
          type: string
        summary:
          type: string
        consequence:
          type: string
        remedy:
          type: string
        recallDate:
          type: string
          format: date

    SafetyRating:
      type: object
      properties:
        overallRating:
          type: integer
          minimum: 1
          maximum: 5
        frontalCrashRating:
          type: integer
          minimum: 1
          maximum: 5
        sideCrashRating:
          type: integer
          minimum: 1
          maximum: 5
        rolloverRating:
          type: integer
          minimum: 1
          maximum: 5

    FuelEconomy:
      type: object
      properties:
        cityMpg:
          type: number
        highwayMpg:
          type: number
        combinedMpg:
          type: number
        annualFuelCost:
          type: number
        fuelType:
          type: string

    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          type: object
          required: [code, message]
          properties:
            code:
              type: string
              description: Machine-readable error code
              example: "VALIDATION_FAILED"
            message:
              type: string
              description: Human-readable error message
              example: "VIN validation failed"
            details:
              type: object
              description: Additional error context
            requestId:
              type: string
              description: Request correlation ID

  responses:
    BadRequest:
      description: Invalid request format or parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error:
              code: "INVALID_REQUEST"
              message: "Invalid VIN format"

    TooManyRequests:
      description: Rate limit exceeded
      headers:
        Retry-After:
          schema:
            type: integer
          description: Seconds to wait before retrying
        X-Rate-Limit-Limit:
          schema:
            type: integer
          description: Request limit per window
        X-Rate-Limit-Remaining:
          schema:
            type: integer
          description: Requests remaining in current window
        X-Rate-Limit-Reset:
          schema:
            type: integer
          description: Rate limit reset time (Unix timestamp)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error:
              code: "RATE_LIMIT_EXCEEDED"
              message: "Too many requests"

tags:
  - name: VIN Decoding
    description: Vehicle identification number decoding operations
  - name: Vehicle Profiles
    description: Comprehensive vehicle data retrieval
  - name: System
    description: System health and monitoring endpoints
