
import { ReportData } from '../pdf/types';

export interface AINSummaryData {
  summary: string;
  keyInsights: string[];
  riskFactors: string[];
  marketPosition: string;
}

export async function generateAINSummaryForPdf(reportData: ReportData): Promise<AINSummaryData> {
  try {
    const prompt = createAINPrompt(reportData);
    
    const response = await fetch('/api/openai/generate-summary', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt,
        vehicleData: {
          year: reportData.year,
          make: reportData.make,
          model: reportData.model,
          vin: reportData.vin,
          mileage: reportData.mileage,
          condition: reportData.condition,
          estimatedValue: reportData.estimatedValue,
          confidenceScore: reportData.confidenceScore
        }
      })
    });

    if (!response.ok) {
      throw new Error('Failed to generate AIN summary');
    }

    const data = await response.json();
    return data.summary;
  } catch (error) {
    console.error('Error generating AIN summary:', error);
    return {
      summary: 'Unable to generate AI summary at this time.',
      keyInsights: ['Market analysis available in detailed report'],
      riskFactors: ['Standard vehicle assessment completed'],
      marketPosition: 'Competitive market value estimated'
    };
  }
}

function createAINPrompt(reportData: ReportData): string {
  return `
As AIN (Automotive Intelligence Network), analyze this vehicle valuation data and provide a professional summary for dealers:

Vehicle: ${reportData.year} ${reportData.make} ${reportData.model}
VIN: ${reportData.vin || 'Not provided'}
Mileage: ${reportData.mileage?.toLocaleString() || 'Unknown'} miles
Condition: ${reportData.condition}
Estimated Value: $${reportData.estimatedValue?.toLocaleString() || 'TBD'}
Confidence Score: ${reportData.confidenceScore || 'N/A'}%

Please provide:
1. A concise 2-3 sentence summary of the vehicle's market position
2. 3-4 key insights about value drivers or concerns
3. 2-3 risk factors dealers should consider
4. Overall market position assessment

Keep the tone professional and dealer-focused. Highlight actionable insights for inventory decisions.
  `.trim();
}

export function formatAINSummaryForPdf(summary: AINSummaryData): string {
  return `
AIN SUMMARY

Market Analysis:
${summary.summary}

Key Insights:
${summary.keyInsights.map(insight => `• ${insight}`).join('\n')}

Risk Factors:
${summary.riskFactors.map(risk => `• ${risk}`).join('\n')}

Market Position: ${summary.marketPosition}

Generated by AIN (Automotive Intelligence Network)
  `.trim();
}
