
import { ReportOptions } from './types';

export const defaultReportOptions: ReportOptions = {
  isPremium: false,
  includeExplanation: false,
  includeComparables: false,
  includeFooter: true,
  includeBranding: true,
  includeAIScore: true,
  includeTimestamp: true,
  includePhotoAssessment: false,
  footerText: 'Generated by Car Detective © ' + new Date().getFullYear(),
  primaryColor: '#3B82F6',
  secondaryColor: '#0F172A',
  fonts: {
    titleFont: 'Helvetica-Bold',
    bodyFont: 'Helvetica',
  }
};
