
import { ReportOptions } from './types';

export const defaultReportOptions: ReportOptions = {
  isPremium: false,
  includeExplanation: false,
  includeFooter: true,
  includeBranding: true,
  includeAIScore: true,
  includeTimestamp: true,
  includePhotoAssessment: false,
  footerText: 'Generated by Car Detective © ' + new Date().getFullYear(),
};
