import { ReportOptions } from "./types";

export const defaultReportOptions: ReportOptions = {
<<<<<<< HEAD
  isPremium: false,
  includeExplanation: false,
  includeFooter: true,
  includeBranding: true,
  includeAIScore: true,
  includeTimestamp: true,
  includePhotoAssessment: false,
  footerText: 'Generated by Car Detective © ' + new Date().getFullYear(),
=======
  pageSize: "letter",
  margins: { top: 72, right: 72, bottom: 72, left: 72 },
  includePageNumbers: true,
  includePhotos: true,
  includeSimilarVehicles: false,
  companyInfo: {
    name: "Car Detective",
    logo: null,
    website: "www.cardetective.com",
    phone: "(800) 555-1234",
  },
>>>>>>> 17b22333 (Committing 1400+ updates: bug fixes, file sync, cleanup)
};
