import { SectionParams } from '../types';

export function drawFooterSection(params: SectionParams) {
  const { doc, pageWidth, margin, regularFont, boldFont } = params;
  const footerText = 'Generated by Vehicle Valuation Tool';
  const pageNumberText = `Page ${doc.page}`;
  const fontSize = 10;

  // Use the correct method to calculate text width based on the PDF library
  const footerTextWidth = doc.widthOfString(footerText, { font: regularFont, size: fontSize });
  const pageNumberTextWidth = doc.widthOfString(pageNumberText, { font: regularFont, size: fontSize });

  const xFooterText = margin;
  const yFooter = doc.pageHeight() - margin - 5;

  doc.font(regularFont, fontSize)
    .fillColor('gray')
    .text(footerText, xFooterText, yFooter, {
      align: 'left',
      width: pageWidth - 2 * margin
    });

  const xPageNumberText = pageWidth - margin - pageNumberTextWidth;

  doc.font(regularFont, fontSize)
    .fillColor('gray')
    .text(pageNumberText, xPageNumberText, yFooter, {
      align: 'right',
      width: pageWidth - 2 * margin
    });
}
