
import { SectionParams } from '../types';

export function drawFooterSection(params: SectionParams): void {
  const { 
    page, 
    data, 
    doc, 
    pageWidth = 600, // Default value if undefined
    textColor = { r: 0, g: 0, b: 0 },
    regularFont 
  } = params;
  
  // Draw footer line
  page.drawLine({
    start: { x: 50, y: 50 },
    end: { x: pageWidth - 50, y: 50 },
    thickness: 1,
    color: { r: 0.8, g: 0.8, b: 0.8 },
  });
  
  // Draw footer text
  page.drawText('Generated by Car Detective', {
    x: 50,
    y: 35,
    size: 9,
    font: regularFont,
    color: textColor,
  });
  
  // Draw date
  const dateText = `Report Date: ${new Date().toLocaleDateString()}`;
  const dateTextWidth = regularFont ? regularFont.widthOfTextAtSize(dateText, 9) : 100;
  
  page.drawText(dateText, {
    x: pageWidth - 50 - dateTextWidth,
    y: 35,
    size: 9,
    font: regularFont,
    color: textColor,
  });
}
