
import { SectionParams } from '../types';

export function drawFooterSection(params: SectionParams) {
  const { doc, pageWidth, margin = 40 } = params;
  const footerText = 'Generated by Vehicle Valuation Tool';
  const pageNumberText = `Page ${doc.page}`;
  const fontSize = 10;

  // Calculate footer position
  const xFooterText = margin;
  const yFooter = doc.pageHeight ? doc.pageHeight() - margin - 5 : 700; // Fallback position

  doc.fontSize(fontSize)
    .fillColor('gray')
    .text(footerText, xFooterText, yFooter, {
      align: 'left',
      width: pageWidth - 2 * margin
    });

  const xPageNumberText = pageWidth - margin - 100;

  doc.fontSize(fontSize)
    .fillColor('gray')
    .text(pageNumberText, xPageNumberText, yFooter, {
      align: 'right',
      width: 100
    });
}
