
import { SectionParams } from '../types';
import { rgb } from 'pdf-lib';

export async function addFooterSection(params: SectionParams): Promise<number> {
  const { page, fonts, options, margin, pageWidth } = params;
  const y = params.y ?? 50;
  
  const footerText = `Generated by ${options.companyInfo.name} - ${options.companyInfo.website}`;
  
  page.drawText(footerText, {
    x: margin,
    y,
    size: 8,
    font: fonts.regular,
    color: rgb(0.5, 0.5, 0.5),
  });
  
  return y - 20;
}
