<<<<<<< HEAD

import { ReportData, ReportOptions } from '../types';
=======
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { ReportData } from "../types";
>>>>>>> 17b22333 (Committing 1400+ updates: bug fixes, file sync, cleanup)

/**
 * Generate a premium PDF report with auction data and AIN summary
 */
export async function generatePremiumReport(
  data: ReportData,
  options: Partial<ReportOptions> = {}
): Promise<Uint8Array> {
  const mergedOptions = {
    isPremium: true,
    includeExplanation: true,
    includeAuctionData: true,
    includeAINSummary: true,
    ...options
  };

  // Ensure auction data is included for premium reports
  const reportData = {
    ...data,
    isPremium: mergedOptions.isPremium,
    auctionResults: data.auctionResults || []
  };

  // Generate enhanced HTML content with auction data and AIN summary
  const htmlContent = generateEnhancedValuationHTML(reportData, mergedOptions);
  
  console.log('🏁 Generating premium PDF with enhanced data:', {
    vehicle: `${data.year} ${data.make} ${data.model}`,
    estimatedValue: data.estimatedValue,
    auctionResults: data.auctionResults?.length || 0,
    hasAINSummary: !!mergedOptions.ainSummary,
    hasDebugInfo: !!mergedOptions.debugInfo,
    isPremium: mergedOptions.isPremium
  });

  // Convert HTML to PDF bytes
  const pdfContent = createPremiumPDFContent(reportData, mergedOptions);
  
  // Convert to Uint8Array
  const encoder = new TextEncoder();
  return encoder.encode(pdfContent);
}

/**
 * Generate enhanced HTML content for the valuation report
 */
<<<<<<< HEAD
function generateEnhancedValuationHTML(data: ReportData, options: ReportOptions): string {
  const auctionSection = generateAuctionSection(data.auctionResults || []);
  const ainSection = options.ainSummary ? generateAINSection(options.ainSummary) : '';
  const debugSection = options.debugInfo ? generateDebugSection(options.debugInfo) : '';
  
  return `
    <div class="valuation-report">
      <!-- Header Section -->
      <div class="header">
        <h1>CarPerfector Premium Valuation Report</h1>
        <div class="vehicle-info">
          <h2>${data.year} ${data.make} ${data.model}</h2>
          ${data.vin ? `<p>VIN: ${data.vin}</p>` : ''}
        </div>
      </div>
      
      <!-- Valuation Summary -->
      <div class="valuation-summary">
        <h3>Estimated Value: $${data.estimatedValue?.toLocaleString()}</h3>
        <p>Confidence Score: ${data.confidenceScore}%</p>
        ${data.priceRange ? `<p>Range: $${data.priceRange[0]?.toLocaleString()} - $${data.priceRange[1]?.toLocaleString()}</p>` : ''}
      </div>
      
      ${auctionSection}
      ${ainSection}
      ${debugSection}
      
      <!-- Watermark Section -->
      <div class="watermark">
        <p>Generated by CarPerfector | Report ID: ${options.trackingId || 'N/A'}</p>
        <p>Generated: ${new Date().toLocaleString()}</p>
      </div>
    </div>
  `;
=======
export async function generateBasicReport(
  props: BasicReportGeneratorProps,
): Promise<void> {
  const {
    pdfDoc,
    page,
    width,
    height,
    margin,
    regularFont,
    boldFont,
    reportData,
  } = props;
  let currentY = height - margin;

  // Add header
  page.drawText("Vehicle Valuation Report", {
    x: margin,
    y: currentY,
    size: 18,
    font: boldFont,
    color: rgb(0.1, 0.1, 0.1),
  });
  currentY -= 20;

  // Add vehicle details
  page.drawText(
    `Vehicle: ${reportData.year} ${reportData.make} ${reportData.model}`,
    {
      x: margin,
      y: currentY,
      size: 12,
      font: regularFont,
      color: rgb(0.3, 0.3, 0.3),
    },
  );
  currentY -= 15;

  page.drawText(`VIN: ${reportData.vin || "Not provided"}`, {
    x: margin,
    y: currentY,
    size: 10,
    font: regularFont,
    color: rgb(0.5, 0.5, 0.5),
  });
  currentY -= 15;

  // Add valuation details
  page.drawText(
    `Estimated Value: $${reportData.estimatedValue.toLocaleString()}`,
    {
      x: margin,
      y: currentY,
      size: 14,
      font: boldFont,
      color: rgb(0.2, 0.7, 0.2),
    },
  );
  currentY -= 20;

  // Add explanation
  const explanationLines = wrapText(
    reportData.explanation,
    regularFont,
    10,
    width - margin * 2,
  );
  page.drawText("Explanation:", {
    x: margin,
    y: currentY,
    size: 12,
    font: boldFont,
    color: rgb(0.3, 0.3, 0.3),
  });
  currentY -= 15;

  for (const line of explanationLines) {
    page.drawText(line, {
      x: margin,
      y: currentY,
      size: 10,
      font: regularFont,
      color: rgb(0.3, 0.3, 0.3),
    });
    currentY -= 12;
  }
>>>>>>> 17b22333 (Committing 1400+ updates: bug fixes, file sync, cleanup)
}

/**
 * Generate auction history section
 */
<<<<<<< HEAD
function generateAuctionSection(auctionResults: any[]): string {
  if (!auctionResults || auctionResults.length === 0) {
    return `
      <div class="auction-section">
        <h3>🏦 Auction History</h3>
        <p>No auction history found for this vehicle.</p>
      </div>
    `;
=======
function wrapText(
  text: string,
  font: any,
  fontSize: number,
  maxWidth: number,
): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let currentLine = "";

  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    const width = font.widthOfTextAtSize(testLine, fontSize);

    if (width <= maxWidth) {
      currentLine = testLine;
    } else {
      lines.push(currentLine);
      currentLine = word;
    }
>>>>>>> 17b22333 (Committing 1400+ updates: bug fixes, file sync, cleanup)
  }

  const auctionItems = auctionResults.slice(0, 5).map(item => `
    <div class="auction-item">
      <strong>${item.auction_source}</strong>: $${parseInt(item.price).toLocaleString()}
      <br/>Date: ${item.sold_date}
      <br/>Condition: ${item.condition_grade || 'Not specified'}
      ${item.location ? `<br/>Location: ${item.location}` : ''}
    </div>
  `).join('');

  return `
    <div class="auction-section">
      <h3>🏦 Auction History</h3>
      <p>Recent auction sales for similar vehicles:</p>
      ${auctionItems}
    </div>
  `;
}

/**
 * Generate AIN summary section
 */
function generateAINSection(ainSummary: string): string {
  return `
    <div class="ain-section">
      <h3>🧠 AI Valuation Analysis</h3>
      <div class="ain-content">
        ${ainSummary.split('\n').map(line => `<p>${line}</p>`).join('')}
      </div>
    </div>
  `;
}

/**
 * Generate debug section (for development)
 */
function generateDebugSection(debugInfo: string): string {
  return `
    <div class="debug-section">
      <h3>🔧 Debug Information</h3>
      <div class="debug-content">
        <pre>${debugInfo}</pre>
      </div>
    </div>
  `;
}

/**
 * Create premium PDF content with enhanced formatting
 */
function createPremiumPDFContent(data: ReportData, options: ReportOptions): string {
  return `%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
>>
endobj

4 0 obj
<<
/Length 200
>>
stream
BT
/F1 12 Tf
50 700 Td
(CarPerfector Premium Valuation Report) Tj
0 -20 Td
(${data.year} ${data.make} ${data.model}) Tj
0 -20 Td
(Estimated Value: $${data.estimatedValue?.toLocaleString()}) Tj
0 -20 Td
(Confidence: ${data.confidenceScore}%) Tj
${data.auctionResults && data.auctionResults.length > 0 ? `
0 -40 Td
(Auction History: ${data.auctionResults.length} records found) Tj
` : ''}
${options.ainSummary ? `
0 -20 Td
(AI Analysis: Included) Tj
` : ''}
0 -40 Td
(Report ID: ${options.trackingId || 'N/A'}) Tj
0 -20 Td
(Generated: ${new Date().toLocaleString()}) Tj
ET
endstream
endobj

xref
0 5
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000215 00000 n 
trailer
<<
/Size 5
/Root 1 0 R
>>
startxref
800
%%EOF`;
}
