name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate no banned patterns
        run: |
          set -e
          echo "🔍 Checking for banned patterns..."
          
          # Check for VITE_ usage (exit 1 if found)
          if git grep -n "import\.meta\.env\.VITE_" -- "src" 2>/dev/null; then
            echo "❌ Found import.meta.env.VITE_ usage"
            exit 1
          fi
          
          # Check for localhost URLs (exit 1 if found)
          if git grep -n "localhost:" -- "src" 2>/dev/null; then
            echo "❌ Found hardcoded localhost URLs"
            exit 1
          fi
          
          # Check for console.log statements (exit 1 if found)
          if git grep -n "console\.log(" -- "src" 2>/dev/null; then
            echo "❌ Found console.log statements"
            exit 1
          fi
          
          # Check for debugger statements (exit 1 if found)
          if git grep -n "debugger;" -- "src" 2>/dev/null; then
            echo "❌ Found debugger statements" 
            exit 1
          fi
          
          echo "✅ No banned patterns found!"

      - name: Lint
        run: npm run lint

      - name: Production lint check
        run: npx eslint src/ --config .eslintrc.production.json

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm test
        env:
          CI: true

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --ci

      - name: Run PDF & Premium E2E tests
        run: npx playwright test e2e/download-and-premium.spec.ts --reporter=github

      - name: Run Explanation Feature E2E tests
        run: npx playwright test e2e/explanation.spec.ts --reporter=github

      - name: Run Valuation Flow E2E tests
        run: npx playwright test e2e/valuation-flow.spec.ts --reporter=github

      - name: Run Stripe Payment Flow E2E tests
        run: npx playwright test e2e/stripe-flow.spec.ts --reporter=github

      - name: Run Dealer Offer Flow E2E tests
        run: npx playwright test e2e/dealer-offer-flow.spec.ts --reporter=github
        
      - name: Run Configuration Smoke Tests
        run: npx playwright test e2e/smoke-config.spec.ts --reporter=github
        
      - name: Run AIN Integration Smoke Tests
        run: npx playwright test e2e/ain-integration-smoke.spec.ts --reporter=github
        env:
          UPSTREAM_HOST: ${{ secrets.AIN_UPSTREAM_HOST || 'jsonplaceholder.typicode.com' }}

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
