name: Repo Audit
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies (workspaces)
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --workspaces --include-workspace-root
          fi

      - name: Run audit
        run: npx --yes tsx apps/ain-valuation-engine/src/scripts/run-audit.mts

      - name: Upload audit artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: repo-audit
          path: |
            logs/**
            **/AUDIT*.md
            **/audit/*.md
          if-no-files-found: ignore

      - name: Job summary
        if: always()
        shell: bash
        run: |
          {
            echo "## Repo Audit";
            echo;
            if [ -f "apps/ain-valuation-engine/FULL_REPOSITORY_AUDIT_REPORT.md" ]; then
              sed -n '1,400p' apps/ain-valuation-engine/FULL_REPOSITORY_AUDIT_REPORT.md
            else
              echo "_No full report file found; check the uploaded artifact._"
            fi
          } >> "$GITHUB_STEP_SUMMARY"
