name: Repo Audit
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install deps
        run: pnpm -w install --frozen-lockfile
      - name: Run audit
        run: pnpm tsx apps/ain-valuation-engine/src/scripts/run-audit.mts
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: repo-audit
          path: |
            .audit/**
            **/AUDIT_REPORT.md
            **/AUDIT_PROGRESS.txt
            **/audit-duplicates-report.txt
            logs/**
