name: Repo Audit

on:
  workflow_dispatch:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (pnpm if present, else npm)
        run: |
          set -e
          if [ -f pnpm-lock.yaml ] || [ -f pnpm-workspace.yaml ]; then
            echo "→ Using pnpm"
            corepack enable
            corepack prepare pnpm@9 --activate
            pnpm --version
            pnpm install --no-frozen-lockfile
          elif [ -f package-lock.json ]; then
            echo "→ Using npm"
            npm ci
          else
            echo "No lockfile found. Running npm install (best-effort)."
            npm install
          fi

      - name: Run audit script via tsx
        run: |
          set -e
          if command -v pnpm >/dev/null 2>&1 && ( [ -f pnpm-lock.yaml ] || [ -f pnpm-workspace.yaml ] ); then
            pnpm exec tsx apps/ain-valuation-engine/src/scripts/run-audit.mts || npx -y tsx apps/ain-valuation-engine/src/scripts/run-audit.mts
          else
            npx -y tsx apps/ain-valuation-engine/src/scripts/run-audit.mts
          fi

      - name: Upload audit artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: repo-audit
          path: |
            .audit/**
            **/AUDIT_REPORT.md
            **/AUDIT_PROGRESS.txt
            **/audit-duplicates-report.txt
            logs/**
